apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "k8s-image-availability-exporter.fullname" . }}
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/name: "{{ template "k8s-image-availability-exporter.fullname" . }}"
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: monitoring
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ template "k8s-image-availability-exporter.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "k8s-image-availability-exporter.fullname" . }}
    spec:
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      containers:
      - name: k8s-image-availability-exporter
        {{- if .Values.k8sImageAvailabilityExporter.args }}
        args:
        {{- range .Values.k8sImageAvailabilityExporter.args }}
          - {{ . }}
        {{- end }}
        {{- end }}
        {{- if .Values.k8sImageAvailabilityExporter.env }}
        env:
        {{- range .Values.k8sImageAvailabilityExporter.env }}
          - name: {{ .name }}
            value: {{ .value }}
        {{- end }}
        {{- end }}
        ports:
        - containerPort: 8080
          name: http
        image: {{ .Values.k8sImageAvailabilityExporter.image.repository }}:{{ .Values.k8sImageAvailabilityExporter.image.tag | default (printf "v%s" .Chart.AppVersion) }}
        imagePullPolicy: {{ .Values.k8sImageAvailabilityExporter.image.imagePullPolicy }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      serviceAccountName: {{ template "k8s-image-availability-exporter.fullname" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
