apiVersion: v1
kind: Service
metadata:
  name: {{ template "k8s-image-availability-exporter.fullname" . }}
  labels:
    app: {{ template "k8s-image-availability-exporter.fullname" . }}
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: {{ template "k8s-image-availability-exporter.fullname" . }}
