---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "k8s-image-availability-exporter.fullname" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - list
      - watch
      - get
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - list
      - watch
      - get
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
      - apps
    resources:
      - deployments
      - daemonsets
      - statefulsets
    verbs:
      - list
      - watch
      - get
  - apiGroups:
      - batch
    resources:
      - cronjobs
    verbs:
      - list
      - watch
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "k8s-image-availability-exporter.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "k8s-image-availability-exporter.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "k8s-image-availability-exporter.fullname" . }}
    namespace: {{ .Release.Namespace }}
