{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "k8s-image-availability-exporter.fullname" . }}
  labels:
    app: {{ template "k8s-image-availability-exporter.fullname" . }}
    {{- if .Values.serviceMonitor.additional_labels.enabled }}
    {{- toYaml .Values.serviceMonitor.additional_labels.prometheus_service_monitor_selector | nindent 4}}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ template "k8s-image-availability-exporter.fullname" . }}
  endpoints:
  - port: http
    interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
