k8sImageAvailabilityExporter:
  image:
    # -- Repository to use for the k8s-image-availability-exporter deployment
    repository: registry.deckhouse.io/k8s-image-availability-exporter/k8s-image-availability-exporter
    # -- Image tag override for the default value (chart appVersion)
    tag: ""
    # -- Image pull policy to use for the k8s-image-availability-exporter deployment
    pullPolicy: IfNotPresent
  # -- Number of instances to deploy for a k8s-image-availability-exporter deployment
  replicas: 1
  # -- Resource limits for k8s-image-availability-exporter
  resources: {}
  # -- Command line arguments for the exporter
  args:
    - --bind-address=:8080

serviceMonitor:
  # -- Create [Prometheus Operator](https://github.com/coreos/prometheus-operator) serviceMonitor resource
  enabled: false
  # -- Scrape interval for serviceMonitor
  interval: 15s

prometheusRule:
  # -- Create [Prometheus Operator](https://github.com/coreos/prometheus-operator) prometheusRule resource
  enabled: false
  # -- Setup default alerts (works only if prometheusRule.enabled is set to true)
  defaultGroupsEnabled: true
  # -- Additional PrometheusRule groups
  additionalGroups: []

# -- Pod [security context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod).
# See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#security-context) for details.
podSecurityContext: {}
  # fsGroup: 2000

# -- Container [security context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container).
# See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#security-context-1) for details.
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
